//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnSDPSvc.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class OoredooCurrSubsStatu
    {
        public int ID { get; set; }
        public string Callingparty { get; set; }
        public string ServiceID { get; set; }
        public string Servicetype { get; set; }
        public string Requestplan { get; set; }
        public string operationid { get; set; }
        public string Desc { get; set; }
        public Nullable<bool> Newer { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
