//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnSDPSvc.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZainSplServices_Subscribers
    {
        public long ID { get; set; }
        public Nullable<long> ZainSplServices_OrderRelationID { get; set; }
        public string UserID { get; set; }
        public string ProductID { get; set; }
        public string ServiceID { get; set; }
        public string ServiceList { get; set; }
        public string UpdateDesc { get; set; }
        public Nullable<bool> RentSuccess { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> ContentIDSeq { get; set; }
        public Nullable<System.DateTime> ContentSentDate { get; set; }
    }
}
